name: t_ragx
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch==2.1.1
  - torchvision
  - torchaudio
  - pip
  - pip:
      - t-ragx
      - fasttext-wheel>=0.9.2
      - elasticsearch>=7.9.1
      - levenshtein~=0.23.0
      - llama-cpp-python~=0.2.54
      - transformers~=4.38.1
      - unbabel-comet>=2.2.1
      - python-dotenv>=0.5.1
      - openai~=1.13.3
      - OpenCC

      - datasets==2.13.1
      - fsspec==2023.9.2
      - fugashi[unidic_lite]

      - jinja2~=3.1.2
      - tqdm~=4.65.0
      - pandas

      - datasets==2.13.1
      - evaluate
      - peft
      - accelerate
      - protobuf

      - fsspec==2023.9.2
      - bitsandbytes>=0.41.3.post2

      - fugashi[unidic_lite]
      - sacrebleu[ja]
      - black
      - flake8
